### ISSUE TITLE
NoMethodError: undefined method `find_or_create_by_name'

### ISSUE THREAD

**Issue by chillum** [wuendsch/jira2redmine#12]
Hi. I do:

```sh
[redmine@redmine redmine]$ RAILS_ENV=production bin/rake jira_migration:migrate_issue_types      
[...]
Migrated Users
rake aborted!
NoMethodError: undefined method `find_or_create_by_name' for #<Class:0x00000004dad230>
/home/redmine/.gem/ruby/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/home/redmine/redmine/lib/tasks/migrate_jira.rake:638:in `block (3 levels) in <top (required)>'
/home/redmine/redmine/lib/tasks/migrate_jira.rake:637:in `each'
/home/redmine/redmine/lib/tasks/migrate_jira.rake:637:in `block (2 levels) in <top (required)>'
Tasks: TOP => jira_migration:migrate_issue_types
(See full trace by running task with --trace)
[redmine@redmine redmine]$ 
```

My `map_jira_to_redmine.yml` looks like:

```yaml
types:
  Bug: Bug
  New Feature: Feature
  Task: Task
```

Bug, Feature and Task trackers exist in Redmine, but I get this error.<br>`jira_migration:test_all_migrations` passes OK.

No clue, where to look next.

**Comment by wuendsch** [comment]
hi, I have merged with a new version of another branch. please try again.

**Comment by chillum** [comment]
Hm, I get this error:

```
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: This relation would create a circular dependency, An issue cannot be linked to one of its subtasks
/home/redmine/.gem/ruby/gems/activerecord-4.2.1/lib/active_record/validations.rb:79:in `raise_record_invalid'
/home/redmine/.gem/ruby/gems/activerecord-4.2.1/lib/active_record/validations.rb:43:in `save!'
/home/redmine/.gem/ruby/gems/activerecord-4.2.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/redmine/.gem/ruby/gems/activerecord-4.2.1/lib/active_record/transactions.rb:291:in `block in save!'
/home/redmine/.gem/ruby/gems/activerecord-4.2.1/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
/home/redmine/.gem/ruby/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/redmine/.gem/ruby/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/home/redmine/.gem/ruby/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/redmine/.gem/ruby/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/home/redmine/.gem/ruby/gems/activerecord-4.2.1/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
/home/redmine/.gem/ruby/gems/activerecord-4.2.1/lib/active_record/transactions.rb:291:in `save!'
/home/redmine/redmine/lib/tasks/migrate_jira.rake:644:in `block in migrate_issue_links'
/home/redmine/redmine/lib/tasks/migrate_jira.rake:628:in `each'
/home/redmine/redmine/lib/tasks/migrate_jira.rake:628:in `migrate_issue_links'
/home/redmine/redmine/lib/tasks/migrate_jira.rake:989:in `block (2 levels) in <top (required)>'
Tasks: TOP => jira_migration:do_all_migrations => jira_migration:migrate_issues
```
